In [ ]:
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
!unzip '/content/drive/MyDrive/Do_An_MachineLearning/UIT-VC.zip'

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
  inflating: UIT-VC/Train/truck/vd0242592.jpg  
  inflating: UIT-VC/Train/truck/vd0242593.jpg  
  inflating: UIT-VC/Train/truck/vd0242594.jpg  
  inflating: UIT-VC/Train/truck/vd0242595.jpg  
  inflating: UIT-VC/Train/truck/vd0242596.jpg  
  inflating: UIT-VC/Train/truck/vd0242597.jpg  
  inflating: UIT-VC/Train/truck/vd0242598.jpg  
  inflating: UIT-VC/Train/truck/vd0242599.jpg  
  inflating: UIT-VC/Train/truck/vd024260.jpg  
  inflating: UIT-VC/Train/truck/vd0242600.jpg  
  inflating: UIT-VC/Train/truck/vd0242601.jpg  
  inflating: UIT-VC/Train/truck/vd0242602.jpg  
  inflating: UIT-VC/Train/truck/vd0242603.jpg  
  inflating: UIT-VC/Train/truck/vd0242604.jpg  
  inflating: UIT-VC/Train/truck/vd0242605.jpg  
  inflating: UIT-VC/Train/truck/vd0242606.jpg  
  inflating: UIT-VC/Train/truck/vd0242607.jpg  
  inflating: UIT-VC/Train/truck/vd0242608.jpg  
  inflating: UIT-VC/Train/truck/vd0242609.jpg  
  inflating: UIT-VC/Train/truck/

In [ ]:
 import numpy as np
import tensorflow as tf
import os
import cv2
from keras.preprocessing import image
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import OneHotEncoder

#truy cập vòa file chứa ảnh
f1=os.path.join("/content/UIT-VC/Train")
print(f1) # in các tên forder trong file f1
data=[]
labels=[]

for i in os.listdir(f1):
    cla=os.path.join(f1,i)
    data1=[]
    for img in os.listdir(cla):
        data1.append(os.path.join(cla,img))
        labels.append(i)
    data.append(data1)

s=0
X=[]
Y=labels
for i in data:
    for j in i:
        s+=1
        try:
            img=cv2.imread(j)
            images=cv2.resize(img,(28,28))
            images2=image.img_to_array(images)
            X.append(images2)
        except Exception as e:
            print(j)
            Y.pop(s-1)
            s-=1
            print(e)


/content/UIT-VC/Train


In [ ]:
print(type(X))
print(len(X))
print(type(X[1]))
print(X[1].shape)

<class 'list'>
69266
<class 'numpy.ndarray'>
(28, 28, 3)


In [ ]:
!rm '/content/UIT-VC/Train/car/vd006855.jpg'
!rm '/content/UIT-VC/Train/van/vd006219.jpg'

In [ ]:
 pip install category_encoders

     |████████████████████████████████| 81kB 9.1MB/s 


In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
le = LabelEncoder()
encoded = le.fit_transform(np.ravel(Y))

In [ ]:
X_tmp=np.array(X,dtype="float32")
X_tmp=np.reshape(X_tmp,(len(Y),-1))
print(X_tmp.shape)


(69266, 2352)


In [ ]:
Y_encode = encoded
from sklearn.svm import SVC
classifier = SVC(kernel ="rbf")
classifier.fit(X_tmp, Y_encode)

In [ ]:
import pickle
from joblib import dump, load

filename = 'Model_SVM_Kernel_rbf'
pickle.dump(classifier, open(filename, 'wb'))


In [ ]:
import numpy as np
import tensorflow as tf
import os
import cv2
from keras.preprocessing import image
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import OneHotEncoder
#truy cập vòa file chứa ảnh
f1=os.path.join("/content/UIT-VC/Test")
print(f1) # in các tên forder trong file f1
data_test=[]
labels_test=[]

for i in os.listdir(f1):
    cla=os.path.join(f1,i)
    data1=[]
    for img in os.listdir(cla):
        data1.append(os.path.join(cla,img))
        labels_test.append(i)
    data_test.append(data1)

s=0
X_test=[]
Y_test=labels_test
for i in data_test:
    for j in i:
        s+=1
        try:
            img=cv2.imread(j)
            images=cv2.resize(img,(28,28))
            images=image.img_to_array(images)
            X_test.append(images2)
        except Exception as e:
            print(j)
            Y_test.pop(s-1)
            s-=1
            print(e)
X_test=np.array(X_test,dtype="float32")
X_test=np.reshape(X_test,(len(Y_test),-1))
print(X_test.shape)
le = LabelEncoder()
Y_test = le.fit_transform(np.ravel(Y_test))

/content/UIT-VC/Test


In [ ]:
!rm '/content/UIT-VC/Test/motor/vd0064779.jpg'
!rm '/content/UIT-VC/Test/truck/vd006418.jpg'

rm: cannot remove '/content/UIT-VC/Test/motor/vd0064779.jpg': No such file or directory
rm: cannot remove '/content/UIT-VC/Test/truck/vd006418.jpg': No such file or directory


(41766, 3136)


In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
le = LabelEncoder()
Y_test = le.fit_transform(np.ravel(Y_test))

In [ ]:
import pickle
filename = '/content/drive/MyDrive/Model_SVM_Kernel_rbf'
classifier = pickle.load(open(filename, 'rb'))

In [ ]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, classifier.predict(X_test))
print(cm)

[[    0     0     1    18     0     1     0     0]
 [    0   196   366    37     0     0    44    22]
 [    0     1  3676   834     0     0   145     8]
 [    0    67  1062 30439     0    12  1271     4]
 [    0     0     1   107     0     0     0     0]
 [    0     0    59   311     0    87    88     0]
 [    0    18   798   780     0     1  1086     4]
 [    0     0   148    15     0     0    17    42]]


In [ ]:
Y_tmp = Y_test
Y_tmp = le.inverse_transform(Y_tmp)
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

{'bicycle': 0, 'bus': 1, 'car': 2, 'motor': 3, 'pedestrian': 4, 'tricycle': 5, 'truck': 6, 'van': 7}


In [ ]:
Y_predict = classifier.predict(X_test)


In [ ]:
from sklearn.metrics import f1_score
f1_score_SVM = f1_score(Y_test,Y_predict,average='weighted')
print(f1_score_SVM)


0.8462537013793879
